#!/bin/sh
APP_NAME=dictionarysearch.xpi
rm ${APP_NAME}.xpi
find . -name "*.xul" -print | zip ${APP_NAME} -@
find . -name "*.js" -print | zip ${APP_NAME} -@
find . -name "*.dtd" -print | zip ${APP_NAME} -@
find . -name "*.properties" -print | zip ${APP_NAME} -@
find . -name "*.png" -print | zip ${APP_NAME} -@

zip ${APP_NAME} install.rdf chrome.manifest

